import pandas as pd
import os
import yaml

sampleinfo = pd.read_table(config["sampleTable"],dtype={"sampleid": str})

SAMPLES=list(sampleinfo.loc[:,"sampleid"])

with open("profiles/slurm/config.yaml") as f:
    slurm_profile_config = yaml.safe_load(f)

DECON_METHODS = config["ambient_decon_methods"]
DOUBLET_METHODS = config["doublet_removal_methods"]
EMPTYDROP_METHODS = config["emptydrop_removal_methods"]
POSTHOC_METHODS = config["posthoc_methods"]

default_target: True


rule all:
    input:
        expand("results/seurat_filtered/filtered_seurat_tenx_" + "{sample}" + "_markergenes.csv",sample=SAMPLES),
        expand("results/emptydrops/filtered_seurat_emptydrops_{sample}_markergenes.csv",sample=SAMPLES),  
        expand("results/soupx/seurat_soupx_{empty_method}_" + "{sample}" + "_markergenes.csv",sample=SAMPLES,empty_method=EMPTYDROP_METHODS),
        expand("results/cellbender/seurat_cellbender_fromraw_{sample}_markergenes.csv",sample=SAMPLES),
        expand("results/{doublet_method}/seurat_{doublet_method}_soupx_{empty_method}_{sample}_markergenes.csv",sample=SAMPLES,doublet_method=DOUBLET_METHODS,empty_method=EMPTYDROP_METHODS),
        expand("results/posthocfilter/seurat_posthocfilt_{posthoc_method}_{doublet_method}_cellbender_fromraw_{sample}_markergenes.csv",sample=SAMPLES,posthoc_method=POSTHOC_METHODS,doublet_method=DOUBLET_METHODS,empty_method=EMPTYDROP_METHODS),
        expand("results/posthocfilter/seurat_posthocfilt_{posthoc_method}_{doublet_method}_soupx_{empty_method}_{sample}_markergenes.csv",sample=SAMPLES,posthoc_method=POSTHOC_METHODS,doublet_method=DOUBLET_METHODS,empty_method=EMPTYDROP_METHODS)

include: "rules/tenx2seuratrds.smk"
include: "rules/soupx.smk"
include: "rules/scdblfinder.smk"
include: "rules/emptydrops.smk"
include: "rules/install_doubletfinder.smk"
include: "rules/doubletfinder.smk"
include: "rules/cellbender.smk"
include: "rules/cellbender2seurat.smk"
include: "rules/soupx_emptydrops.smk"
include: "rules/posthocfilter_mad.smk"
include: "rules/posthocfilter_threshold.smk"
include: "rules/markers.smk"
