import pandas as pd
import os
import yaml

sampleinfo = pd.read_table(config["sampleTable"],dtype={"sampleid": str})

SAMPLES=list(sampleinfo.loc[:,"sampleid"])

with open("profiles/slurm/config.yaml") as f:
    slurm_profile_config = yaml.safe_load(f)

DECON_METHODS = config["ambient_decon_methods"]
DOUBLET_METHODS = config["doublet_removal_methods"]

rule all:
    input:
        expand("results/{doublet_method}/seurat_{doublet_method}_{decon_method}_" + "{sample}" + ".rds",sample=SAMPLES,doublet_method=DOUBLET_METHODS,decon_method=DECON_METHODS),
        expand("results/emptydrops/seurat_emptydrops_{sample}.rds", sample=SAMPLES),
        "results/doubletfinder_installed.txt",
        expand("results/{doublet_method}/seurat_{doublet_method}_{decon_method}_{sample}.rds",sample=SAMPLES,doublet_method=DOUBLET_METHODS,decon_method=DECON_METHODS)
        
    default_target: True

include: "rules/tenx2seuratrds.smk"
include: "rules/soupx.smk"
include: "rules/scdblfinder.smk"
include: "rules/emptydrops.smk"
include: "rules/install_doubletfinder.smk"
include: "rules/doubletfinder.smk"
